### ISSUE TITLE
Could you please publish a new release?

### ISSUE THREAD

**Issue by tim-eucalyptus** [ilap/bip32-ed25519-dart#3]
Our builds broke since pinnacle updated to 0.3.5 yesterday. It'd be great if you could republish.

Also please consider taking the `^` away from the dependency definition to prevent future issues:

```
dependencies:
  pinenacl: ^0.3.5
```

**Comment by ilap** [comment]
Hi,

Sorry, I have just published the `v0.2.2` and bumped the `v0.3.1` codebase to the `v0.4.0` due to the API break changes, to keep API breaks out of the minor releases. 

I will keep the caret symbol as there should not be any API breaks in patch releases.
Even in minor releases but major, though it would be very inconvenient to have API breaks only in major releases.

Also, I retracted the relevant `pinenacl-dart v0.3.5` and the `bip32-ed25519-dart v0.3.1` packages from `pub.dev`.

So, pls use the `v0.2.2` until you migrate (highly recommended) your code to the `v0.4.0`.


So, sorry for any inconvenience caused by this.

Cheers,

Pal
